// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the one and only unit of data the framework moves between a
// child and its parent. kind is opaque to the framework — it exists purely
// so the service built on top of this framework can distinguish what it put
// in payload ("log", "config", or anything else it invents later) without
// requiring any change to this proto or to the transport/node packages.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StreamMessage carries an Envelope in exactly one direction on the shared
// bidirectional stream: upstream (child -> parent) or downstream
// (parent -> child). The framework forwards each direction recursively
// (upstream keeps going up if this node itself has a parent; downstream
// keeps going down to this node's own children) without inspecting kind.
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Direction:
	//
	//	*StreamMessage_Upstream
	//	*StreamMessage_Downstream
	Direction     isStreamMessage_Direction `protobuf_oneof:"direction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMessage) GetDirection() isStreamMessage_Direction {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *StreamMessage) GetUpstream() *Envelope {
	if x != nil {
		if x, ok := x.Direction.(*StreamMessage_Upstream); ok {
			return x.Upstream
		}
	}
	return nil
}

func (x *StreamMessage) GetDownstream() *Envelope {
	if x != nil {
		if x, ok := x.Direction.(*StreamMessage_Downstream); ok {
			return x.Downstream
		}
	}
	return nil
}

type isStreamMessage_Direction interface {
	isStreamMessage_Direction()
}

type StreamMessage_Upstream struct {
	Upstream *Envelope `protobuf:"bytes,1,opt,name=upstream,proto3,oneof"`
}

type StreamMessage_Downstream struct {
	Downstream *Envelope `protobuf:"bytes,2,opt,name=downstream,proto3,oneof"`
}

func (*StreamMessage_Upstream) isStreamMessage_Direction() {}

func (*StreamMessage_Downstream) isStreamMessage_Direction() {}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x04node\"f\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"|\n" +
	"\rStreamMessage\x12,\n" +
	"\bupstream\x18\x01 \x01(\v2\x0e.node.EnvelopeH\x00R\bupstream\x120\n" +
	"\n" +
	"downstream\x18\x02 \x01(\v2\x0e.node.EnvelopeH\x00R\n" +
	"downstreamB\v\n" +
	"\tdirection2E\n" +
	"\vNodeService\x126\n" +
	"\x06Stream\x12\x13.node.StreamMessage\x1a\x13.node.StreamMessage(\x010\x01B(Z&github.com/anbebong/multi-region/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_node_proto_goTypes = []any{
	(*Envelope)(nil),      // 0: node.Envelope
	(*StreamMessage)(nil), // 1: node.StreamMessage
}
var file_proto_node_proto_depIdxs = []int32{
	0, // 0: node.StreamMessage.upstream:type_name -> node.Envelope
	0, // 1: node.StreamMessage.downstream:type_name -> node.Envelope
	1, // 2: node.NodeService.Stream:input_type -> node.StreamMessage
	1, // 3: node.NodeService.Stream:output_type -> node.StreamMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	file_proto_node_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamMessage_Upstream)(nil),
		(*StreamMessage_Downstream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
