// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Upstream_FullMethodName   = "/node.NodeService/Upstream"
	NodeService_Downstream_FullMethodName = "/node.NodeService/Downstream"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService exposes upstream and downstream as two independent RPCs
// (rather than a single bidirectional stream carrying both directions) so
// that a slow/blocked send in one direction can never stall delivery in the
// other. A child opens both when it connects to a parent; each is its own
// TCP/HTTP2 connection under the hood.
type NodeServiceClient interface {
	// Upstream is a client-streaming RPC: the child keeps sending Envelopes as
	// it produces them; the parent acks once when the child closes the
	// stream. The child's claimed node-id travels as the "node-id" gRPC
	// metadata header on the call, exactly as before.
	Upstream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, Ack], error)
	// Downstream is a server-streaming RPC: the child opens it once (empty
	// request) and the parent pushes Envelopes down it for as long as the
	// child stays connected. The child's claimed node-id also travels as the
	// "node-id" gRPC metadata header on this call.
	Downstream(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Upstream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_Upstream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_UpstreamClient = grpc.ClientStreamingClient[Envelope, Ack]

func (c *nodeServiceClient) Downstream(ctx context.Context, in *Ack, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_Downstream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ack, Envelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownstreamClient = grpc.ServerStreamingClient[Envelope]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService exposes upstream and downstream as two independent RPCs
// (rather than a single bidirectional stream carrying both directions) so
// that a slow/blocked send in one direction can never stall delivery in the
// other. A child opens both when it connects to a parent; each is its own
// TCP/HTTP2 connection under the hood.
type NodeServiceServer interface {
	// Upstream is a client-streaming RPC: the child keeps sending Envelopes as
	// it produces them; the parent acks once when the child closes the
	// stream. The child's claimed node-id travels as the "node-id" gRPC
	// metadata header on the call, exactly as before.
	Upstream(grpc.ClientStreamingServer[Envelope, Ack]) error
	// Downstream is a server-streaming RPC: the child opens it once (empty
	// request) and the parent pushes Envelopes down it for as long as the
	// child stays connected. The child's claimed node-id also travels as the
	// "node-id" gRPC metadata header on this call.
	Downstream(*Ack, grpc.ServerStreamingServer[Envelope]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Upstream(grpc.ClientStreamingServer[Envelope, Ack]) error {
	return status.Error(codes.Unimplemented, "method Upstream not implemented")
}
func (UnimplementedNodeServiceServer) Downstream(*Ack, grpc.ServerStreamingServer[Envelope]) error {
	return status.Error(codes.Unimplemented, "method Downstream not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Upstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).Upstream(&grpc.GenericServerStream[Envelope, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_UpstreamServer = grpc.ClientStreamingServer[Envelope, Ack]

func _NodeService_Downstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ack)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).Downstream(m, &grpc.GenericServerStream[Ack, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownstreamServer = grpc.ServerStreamingServer[Envelope]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upstream",
			Handler:       _NodeService_Upstream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Downstream",
			Handler:       _NodeService_Downstream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/node.proto",
}
